version: "3.7"
services:
  yaichi:
    image: mtsmfm/yaichi
    ports:
      - "80:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  kauth:
    image: ruby:2.6.5-buster
    working_dir: /app
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    environment:
      DATABASE_URL: mysql2://root:root@kauth-mysql:3306
    volumes:
      - "./kauth:/app:cached"
      - "kauth-bundle:/usr/local/bundle"
    depends_on:
      - kauth-mysql
  kauth-mysql:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "kauth-mysql:/var/lib/mysql"
      - "./kauth-mysql/conf.d:/etc/mysql/conf.d"
volumes:
  kauth-bundle:
  kauth-mysql:
